### ISSUE TITLE
New logo/icon proposal

### ISSUE THREAD

**Issue by mansya** [ekazpraw/websisfoakademik_htb#1]
Good day sir. I am a graphic designer and i am interested in designing a logo for your good project. I will be doing it as a gift for free. I just need your permission first before I begin my design. Hoping for your positive feedback. Thanks

**Comment by mansya** [comment]
hi sir. how about this offer? are you interested ?

**Comment by ekazpraw** [comment]
hello sir, i'm a graphic designer too, but im interested about your logo if that is free design, because i'm a organization of build a humanity for studying. thx.
